# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('user_email', models.EmailField(max_length=128, unique=True)),
                ('user_phone', models.BigIntegerField(unique=True)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('department', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='app.Department')),
            ],
        ),
    ]
